### ISSUE TITLE
Unable to add custom schemas at startup

### ISSUE THREAD

**Issue by Shgb1618** [simpleidserver/SimpleIdServer#42]
I've tried using the suggested `SCIMSchemaBuilder` helper  and `.AddSchemas()` in order to add a custom schema at startup, but I'm still getting a 

> schemas are unknown

 scim error response when I try to use the schema I defined. Any idea what I might be doing wrong?

My code:

`List<SCIMSchema> customSchemas = new List<SCIMSchema>();
            var dog = SimpleIdServer.Scim.Builder.SCIMSchemaBuilder.Create("urn:dog")
                .AddStringAttribute("name")
                .AddStringAttribute("breed")
                .Build();
            customSchemas.Add(dog);

            services.AddSIDScim(_ =>
            {
                _.IgnoreUnsupportedCanonicalValues = false;
            }).AddSchemas(customSchemas);

            var schemas = new List<SCIMSchema>
            {
                userSchema,
                groupSchema
            };
            services.AddScimStoreMongoDB(opt =>
            {
                opt.ConnectionString = "mongodb://localhost:27017";
                opt.Database = databaseName;

                opt.CollectionMappings = "mappings";
                opt.CollectionRepresentations = "representations";
                opt.CollectionSchemas = "schemas";
            }, schemas,
            new List<SCIMAttributeMapping>
            {
                new SCIMAttributeMapping
                {
                    Id = Guid.NewGuid().ToString(),
                    SourceResourceType = SCIMConstants.StandardSchemas.UserSchema.ResourceType,
                    SourceAttributeSelector = "groups",
                    TargetResourceType = SCIMConstants.StandardSchemas.GroupSchema.ResourceType,
                    TargetAttributeId = groupSchema.Attributes.First(a => a.Name == "members").SubAttributes.First(a => a.Name == "value").Id
                }
            });`

**Comment by simpleidserver** [comment]
By default, there are two types of resources exposed by the SCIM API : **/Users** and **/Groups**.
To add a new one, you should **create a new Controller** and **register the schema** in the Startup.cs.

We add an example in the **SimpleIdServer.Scim.Startup** project, you can see the changes here : https://github.com/simpleidserver/SimpleIdServer/commit/12938d7b9582de3b0258e73f56b615dd6390cabe

**Comment by Shgb1618** [comment]
Thank you!

Another issue I'm having is that if I make a POST request with a standard User payload, it stores the following structure without any of the additional attributes.

![Screenshot 2020-05-26 at 18 26 04](https://user-images.githubusercontent.com/37128256/82925766-7bcdc500-9f7e-11ea-9b97-4be9718d9385.png)

I've tried adding the additional attributes as new mappings like in the following snippet, but I've been unsuccessful in getting it to write them to the DB.

![Screenshot 2020-05-26 at 18 29 31](https://user-images.githubusercontent.com/37128256/82926136-0ca4a080-9f7f-11ea-8edf-4ade5da21a59.png)

Any help is much appreciated!

**Comment by simpleidserver** [comment]
The SCIMAttributeMapping is used by the API to specify a dependency between a **source  and a target attribute**.
For example : When a **User** is created with or more groups are specified in the attribute **groups**, then  when the group is fetched its property **members** is automatically deduced.

The acceptance test "Check group can be updated with multiple users" explains the workflow (https://github.com/simpleidserver/SimpleIdServer/blob/master/tests/SimpleIdServer.Scim.Host.Acceptance.Tests/Features/Groups.feature).

To add a user, an HTTP POST request must be executed with the correct JSON structure for example :

```
   POST /Users  HTTP/1.1
   Host: example.com
   Accept: application/scim+json
   Content-Type: application/scim+json
   Authorization: Bearer h480djs93hd8
   Content-Length: ...

   {
     "schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],
     "userName":"bjensen",
     "externalId":"bjensen",
     "name":{
       "formatted":"Ms. Barbara J Jensen III",
       "familyName":"Jensen",
       "givenName":"Barbara"
     }
   }
```

**Comment by Shgb1618** [comment]
Even if I make a POST request with the exact json you have in the example above, it writes the object to the DB as defined in the `SCIMRepresentationModel`, except it's missing any of the attributes that would correspond to the `SCIMRepresentationAttributeModel`. (userName and name in this case)

**Comment by simpleidserver** [comment]
When i'm executing an HTTP POST REQUEST against my SCIM API, I get the following result :

**Request** : 

```
GET http://localhost:60002/Users/44a07b8f-e562-4b27-a206-bc2ecb129e4b HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: localhost:60002
Content-Length: 266


   {
     "schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],
     "userName":"bjensen",
     "externalId":"bjensen",
     "name":{
       "formatted":"Ms. Barbara J Jensen III",
       "familyName":"Jensen",
       "givenName":"Barbara"
     }
   }
```

**Result** : 

```
HTTP/1.1 200 OK
Date: Wed, 27 May 2020 16:37:46 GMT
Content-Type: application/scim+json
Server: Kestrel
Content-Length: 687
ETag: fd167c6e-2674-4773-a3f8-ac2dabfd7ead
Location: http://localhost:60002/Users/44a07b8f-e562-4b27-a206-bc2ecb129e4b

{
  "id": "44a07b8f-e562-4b27-a206-bc2ecb129e4b",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "meta": {
    "resourceType": "Users",
    "created": "2020-05-27T16:37:07.3025111",
    "lastModified": "2020-05-27T16:37:07.3026385",
    "version": "fd167c6e-2674-4773-a3f8-ac2dabfd7ead",
    "location": "http://localhost:60002/Users/44a07b8f-e562-4b27-a206-bc2ecb129e4b"
  },
  "externalId": "bjensen",
  "formatted": "Ms. Barbara J Jensen III",
  "name": {
    "formatted": "Ms. Barbara J Jensen III",
    "familyName": "Jensen",
    "givenName": "Barbara"
  },
  "familyName": "Jensen",
  "givenName": "Barbara",
  "userName": "bjensen"
}

```

Your SCIM Schema is probably not complete, can-you check if your Schema is correct by calling the URL "http://localhost:60002/Schemas" ?

**Comment by Shgb1618** [comment]
The response to the /Schemas call:
https://pastebin.com/jH7kKYZV

**Comment by simpleidserver** [comment]
We committed a sample project in the repository. Can-you execute the following steps to have an up and running solution on your local machine ?
1. Open a command prompt and navigate to the directory `samples/UseSCIM/src/UseSCIM.Host`
2. Open the `appsettings.json` file and update the connection string.
3. Execute the command `dotnet ef database update` to migrate the database.
4. Execute the command `dotnet run` to launch the application.
5. Open fiddler or Postman and execute the following HTTP POST REQUEST

```
POST http://localhost:60002/Users HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: localhost:60002
Content-Length: 266


   {
     "schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],
     "userName":"bjensen",
     "externalId":"bjensen",
     "name":{
       "formatted":"Ms. Barbara J Jensen III",
       "familyName":"Jensen",
       "givenName":"Barbara"
     }
   }

```
6. Execute an HTTP GET request ` http://localhost:60002/Users/<id>` you should have something like this :

```
GET http://localhost:60002/Users/<id> HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: localhost:60002
Content-Length: 266


   {
     "schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],
     "userName":"bjensen",
     "externalId":"bjensen",
     "name":{
       "formatted":"Ms. Barbara J Jensen III",
       "familyName":"Jensen",
       "givenName":"Barbara"
     }
   }

```

**Comment by Shgb1618** [comment]
Thanks, but the version I'm trying to get to work is the MongoDB one, not EF.

**Comment by simpleidserver** [comment]
We committed an another sample project in the repository for MongoDB :). 
Can-you execute the following steps to have an up and running solution on your local machine ?

1. Create an empty MongoDB database named `scim`.
2. Open a command prompt and navigate to the directory samples/UseSCIMMongoDb/src/UseSCIM.Host.
3. Open the file `Startup.cs` and check the connection string is correct.
4. Run the command `dotnet run`
5. Open fiddler or Postman and execute the following HTTP POST REQUEST
```
POST http://localhost:60002/Users HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: localhost:60002
Content-Length: 266


   {
     "schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],
     "userName":"bjensen",
     "externalId":"bjensen",
     "name":{
       "formatted":"Ms. Barbara J Jensen III",
       "familyName":"Jensen",
       "givenName":"Barbara"
     }
   }
```
   
6. Execute an HTTP GET request http://localhost:60002/Users/<id> you should have something like this :

```
GET http://localhost:60002/Users/<id> HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: localhost:60002
Content-Length: 266


   {
     "schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],
     "userName":"bjensen",
     "externalId":"bjensen",
     "name":{
       "formatted":"Ms. Barbara J Jensen III",
       "familyName":"Jensen",
       "givenName":"Barbara"
     }
   }

```

**Comment by Shgb1618** [comment]
I've done all of the above and the object that gets writte to the DB is still the following:

![Screenshot 2020-05-29 at 16 37 06](https://user-images.githubusercontent.com/37128256/83272119-13275800-a1cb-11ea-8158-ab5e22b873ee.png)

I haven't made any changes to the sample project and I'm on MongoDB 4.2.0.
I'll go ahead and try again in a Windows VM and I'll report back.

**Comment by simpleidserver** [comment]
We found the issue, when the project is started the SCIM Schema is not correctly stored in the MongoDB. 
In fact the enumeration value is always equal to 0. The code is working on Windows but not on Linux :(.

The issue has been fixed in the master branch, can-you drop your `scim` database and launch the project `samples\UseSCIMMongoDb\src\UseSCIM.Host`.

Sorry for the inconvenience

**Comment by Shgb1618** [comment]
Thanks, I appreciate the help.
I have just one last question: With my currect configuration when I try to POST an enterprise user, I'm getting a schema unknown error. Is there something I need to do to enable the enterprise:2.0:User extension?

**Comment by Shgb1618** [comment]
I found that if I add the enterpriseUser schema as a json and parse it like the core schemas, I'm getting a proper response if I call the `Schemas/urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` endpoint.
However, posting a resource with the enterpriseUser schema included, I'm still getting the following error:
`the schemas urn:ietf:params:scim:schemas:extension:enterprise:2.0:User are unknown`

I've tried adding it to the user schema's extensions as per the screenshot below, but that results in the following error:
`attribute urn:ietf:params:scim:schemas:extension:enterprise:2.0:User is not recognized by the SCIM schema`

<img width="995" alt="Screenshot 2020-06-11 at 19 35 06" src="https://user-images.githubusercontent.com/37128256/84420685-b1c7a600-ac1a-11ea-899d-744b2ab4dbc1.png">

**Comment by simpleidserver** [comment]
The sample project "src\Scim\SimpleIdServer.Scim.Startup" has been updated and the schema "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" is defined as an extension schema : https://github.com/simpleidserver/SimpleIdServer/tree/master/src/Scim/SimpleIdServer.Scim.Startup

Now the "User" resource has 2 schemas "urn:ietf:params:scim:schemas:core:2.0:User" and "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User". Can you execute the sample project "src\Scim\SimpleIdServer.Scim.Startup" and post the following HTTP POST request to create a user ?

  ```
POST http://localhost:60002/Users/ HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: localhost:60002
Content-Length: 361

 {
     "schemas":["urn:ietf:params:scim:schemas:core:2.0:User", "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],
     "userName":"bjensen",
     "externalId":"bjensen",
     "name":{
       "formatted":"Ms. Barbara J Jensen III",
       "familyName":"Jensen",
       "givenName":"Barbara"
     },
    "employeeNumber": "123456"
   }
```

You should receive a response like this:

```
HTTP/1.1 201 Created
Date: Thu, 11 Jun 2020 18:39:29 GMT
Content-Type: application/scim+json
Server: Kestrel
Content-Length: 689
ETag: 0f2bbbe3-1c88-4bb1-b2f2-6099863723e0
Location: http://localhost:60002/Users/733fe63d-0529-4c6c-b2cb-5ddd6f78a103

{
  "id": "733fe63d-0529-4c6c-b2cb-5ddd6f78a103",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User",
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
  ],
  "meta": {
    "resourceType": "Users",
    "created": "2020-06-11T18:39:29.7132463Z",
    "lastModified": "2020-06-11T18:39:29.7133267Z",
    "version": "0f2bbbe3-1c88-4bb1-b2f2-6099863723e0",
    "location": "http://localhost:60002/Users/733fe63d-0529-4c6c-b2cb-5ddd6f78a103"
  },
  "externalId": "bjensen",
  "userName": "bjensen",
  "name": {
    "formatted": "Ms. Barbara J Jensen III",
    "familyName": "Jensen",
    "givenName": "Barbara"
  },
  "employeeNumber": "123456"
}
```
