### ISSUE TITLE
Problems encountered during testing

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#710]
When I click on a User's "Sessions", let's say his list has 10 data, when the data is loaded, I click on "User" at the top to go back to the user list:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/acfc99d0-21dd-4552-bb19-1afbd08ebe83)
This time I clicked on a user who had never logged in, and then went to his "Sessions", I found that his list was still the same as my previous user list (the same 10 pieces of data), he did not refresh. The list only refreshes when I refresh the browser.

**Comment by qq1176914912** [comment]
About the client type: whether the "Name" of the two "SAML" and "Device" are required, I found that in addition to these two clients, the "Name" field of the remaining clients is not required.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/071e8dc0-8d07-4c65-9529-723e2d125ad2)

**Comment by qq1176914912** [comment]
In the "API Resources" of "Scope", when I have some data and have checked it, when I want to delete some data separately, click Delete behind the data I want to delete, and it will delete all the data I have checked before. It is suggested to add the methods of single deletion and multi-selection deletion.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/79f86d10-1ca0-446c-8a63-fe2e7c9a940e)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ce92b750-8c46-4a4f-97a5-6ea08ee66b2e)

**Comment by qq1176914912** [comment]
The Value in the "add Add API resource" method is not displayed in the "API Resources" list, and if you use aud to restrict the api, he only uses "Audience".
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/5bbebed2-5cbe-4554-8a40-a981977d9a9c)

**Comment by simpleidserver** [comment]
**User Session**

The user session refresh has been addressed and fixed in the master branch.

**Name is Required**

The name is no longer required for the client Device and Saml in the master branch.

**Removal**

In the master branch, only the selected elements (client, scopes, API resources, etc.) can now be removed.

**API Resource - Value**

The value corresponds to the description of the API Resource. The translation has been fixed, and the description is displayed in the table.

**Comment by qq1176914912** [comment]
> **User Session**
> 
> The user session refresh has been addressed and fixed in the master branch.
> 
> **Name is Required**
> 
> The name is no longer required for the client Device and Saml in the master branch.
> 
> **Removal**
> 
> In the master branch, only the selected elements (client, scopes, API resources, etc.) can now be removed.
> 
> **API Resource - Value**
> 
> The value corresponds to the description of the API Resource. The translation has been fixed, and the description is displayed in the table.

**Removal**
"API Resources" is special, because the logic here is that it will only apply when it is checked and clicked "Update", and every time it enters the page, the applied resources will be automatically checked, and the list will list all the resources, no matter which "Scope" is created, will be displayed here. If Delete by check is also used here, then the deletion logic is contradictory to the application resource logic. If so, if I want to delete a resource, I need to remove the check box of my application before I can delete the resource I want to delete. If I do not remove the check box, then he will delete the resource that I have already applied (checked state).

**Comment by qq1176914912** [comment]
**User**
In the user groups, when I Assign a group to a user, suppose I first click "Assign groups" to assign a group to the account, and then after I click "Assign groups" button again, the pop-up window will be closed, and the group I added before will disappear. The group I first added appears only when I click another button to switch back again.

**Comment by qq1176914912** [comment]
**Auditing**
Display Only Errors in the audit is invalid
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/b8eecf6e-456f-4294-b477-afbe246d3925)

**Comment by qq1176914912** [comment]
**Remember me**
The "Remember me" function of 5001 login address does not seem to work, I operate like this, I want to access 5001/master, enter the default account password (administrator) and select "Remember me", after successful login, Click "Disconnect" on 5001/master to exit login, and then click "Authenticate" again to jump to the login page, but I didn't remember my last login account and password, and the same is true when logging out from 5002 to the 5001 login page. I am using a browser that is "MIcrosoft Edge" and does not have Traceless mode turned on.
Is this "Remember me" function used to remember the account number and password?

**Comment by qq1176914912** [comment]
**Forget my password**
I noticed that the Forget Password function is used to determine whether it is added by the "CanResetPassword" property, where is this property set? Is it 5002?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/8ae07224-dd60-4112-bfaa-147315a1aab2)
I also found that when I type a wrong password once, the "Forget my password" button disappears:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/2bd9783c-e20a-4a82-8750-0e43ee768f73)

**Comment by qq1176914912** [comment]
As shown below:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/e5e82228-a22a-4eb9-8ff3-411fee769446)
Why are some clients empty and others have values? What values are displayed for the client here? Is the Identifier value of the client obtained or the Name value? If you are getting the Name value, which may be empty due to translation problems, can you get the Identifier value instead?

**Comment by simpleidserver** [comment]
**API Resource**

The UI has been reworked, and the modifications are available in the master branch.

**Group is not Displayed**

I cannot reproduce the problem on my local machine. Can you describe all the steps?

**Display Only Errors**

The issue is fixed in the master branch.

**Remember Me**

The "Remember Me" function is not used to remember the account number and password, but to persist the user's session cookie. Even if the browser is closed, the user's session remains active and is stored in the cookie.

**Forget My Password**

Indeed, the property CanResetPassword is used to display or hide the action. I made some changes in the master branch to fix the problem.

**Client is not Displayed**

By default, the client name is displayed. If the translation doesn't exist, then nothing is displayed. I made some modifications in the master branch to display the ClientId when there is no translation.

**Comment by qq1176914912** [comment]
> Owner

**API Resource**
Thank you for your change, I have seen your modification, do you feel that the page layout is a little awkward, because all the list of resources and the use list are displayed in one page, it seems a little crowded, I have a suggestion that you can consider, separate the two pages, one page for creating new resources, the other page for allocating the use of resources, I think that might be easy to understand, don't you?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/31bdbcd5-2a39-4c56-9a01-2bc4f35a1c77)
This is just one of my thoughts, and if you have a good way to make it easier for people to understand, you can ignore my thoughts.
**Display Only Errors**
The first step is to find a user that doesn't have any groups.
I recorded a video for you:
https://github.com/simpleidserver/SimpleIdServer/assets/79817742/1d650593-7cf5-42f9-9f7d-284e2bd6f745

**Comment by qq1176914912** [comment]
**External login**
I have configured a new third-party login (wechat), I can click on the third login on the 5001 login page to normally jump to login:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/bcd66046-fc04-4d4d-bdec-566b8eed8262)
But when I go to the 5001 page and click login at this location, there is a problem:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/dfd56155-9350-4f22-84e1-328e998fbe86)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/5f967fb7-f332-483a-8710-95545235d739)
So what's going on here? I tried other login, there is a problem with wechat login, other no problem, this is why? If the parameters are missing, why can you jump normally in the login page?

**Comment by qq1176914912** [comment]
**Credentials**
1、I tried "Enroll credentials" on the 5001 page and I clicked on the sms:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/7df38f5f-cd13-4288-9c74-b36cf4469944)
I successfully passed sms authentication and can see it on page 5002:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f5edf299-3961-45d5-8663-23f8b4fc6524)
On the 5001 page, why is the sms button still under "Enroll credentials" and not under "Update your credentials"?
I did not find this to be the case with Email, which automatically goes to "Update your credentials" below when I certify it.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/36038494-7e71-4ae4-813f-ac0b83c03e8b)

2、And I found that all the "Authentication methods" did not have a return button after the authentication was successful, and could only click the previous page from the browser.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f734c16b-1c63-424e-8f58-8ce050d64d48)

**Comment by qq1176914912** [comment]
**Register user **
When I use email to register a user, I randomly enter 123 in the email address, and after clicking Send, an error will be reported, which requires a format judgment, and whether the current email exists is indicated after I receive the verification code and click confirm. Should I apply this judgment before clicking Send button (for registration only)?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/91b60282-a419-4716-a691-a6700552ba3e)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/dcba8b3c-779c-4ab8-a655-3edb50473f5f)

**Comment by qq1176914912** [comment]
**Email registration page**
Why did you set this to 3 input fields?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/c1b93940-8d92-4f94-8489-cf67b583fb2e)
Can I change it to 2 input boxes, like this:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/12018645-6ecb-4deb-9864-6b39e44e68b0)

**Comment by qq1176914912** [comment]
**Registration Workflows**
I used "webauthn" in "Registration Workflows" to register new users, and when it was created, I found that the display name on the "webauthn" registration page was not applied, either "First name" or "Last name". These two values are still blank.

**Comment by qq1176914912** [comment]
**Registration Workflows**
Click the "webauth" button in the 5001 address to add credentials:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/184e5963-c904-42ae-af2a-6d0201fd70e9)
When I successfully obtain the password through the fingerprint verification, the page will not respond, will be stuck here.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/04cafa8c-e085-4743-9413-ae64c2628c12)
But the credentials have already been added to the account.
I also found that if I repeat the above, he can keep adding credentials to the account:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/3ea893f1-11fc-42d9-a228-428ff941cf60)
Moreover, these duplicate credentials cannot be deleted. After clicking delete in the user and refreshing the page again, the deleted credentials are still there and can only be deleted in the data.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/4329569b-300b-424c-a18a-ac5ec1a5f98c)

**Comment by simpleidserver** [comment]
**API Resource**

I agree that the previous implementation was a bit awkward and didn't follow the same logic used in the rest of the application. 
However, in the new implementation, I'm using a standard logic that is used in other applications. 
You can find this component in Material UI for Angular: Material Angular Drag and Drop - Disabled Sorting (https://material.angular.io/cdk/drag-drop/overview#disabled-sorting).
I think it is better to have the available and assigned resources in one view to decrease the number of clicks needed to assign/unassign resources and to offer better visibility.

**Group Disappearance**

The issue has been fixed in the master branch. Now, the groups do not disappear when the window popup is closed.

**Exception: WexinAuthenticationHandler**

The exception is probably thrown because the redirect URL is not passed in the AuthenticationProperties. 
I made some modifications in the master branch to pass this information. Can you try again?

**Sms is still displayed under enroll credentials**

The algorithm used to check if the user has the claim was not correct and has been fixed in the master branch.

**When Credential is Updated, Add a Link to Redirect to the Previous Page**

The returnUrl was not passed in the HTTP request. 
This issue has been fixed in the master branch.

**Ignore unhandled exception**

 have added logic in the Startup.cs to ignore the Developer Exception Middleware when the development mode is set to false. 
 When an exception is thrown, you will be redirected to the /Error page.

**Email validation**

I have added email validation logic in the backend.

**Keep 2 fields (SMS & Email)**

The UI (SMS & email) has been updated to keep only two fields.

**Webauthn problem**

It is now possible to update the webauthn credential on the Identity Server website. The remove feature is also fixed.

**Comment by qq1176914912** [comment]
> **API Resource**
> 
> I agree that the previous implementation was a bit awkward and didn't follow the same logic used in the rest of the application. However, in the new implementation, I'm using a standard logic that is used in other applications. You can find this component in Material UI for Angular: Material Angular Drag and Drop - Disabled Sorting (https://material.angular.io/cdk/drag-drop/overview#disabled-sorting). I think it is better to have the available and assigned resources in one view to decrease the number of clicks needed to assign/unassign resources and to offer better visibility.
> 
> **Group Disappearance**
> 
> The issue has been fixed in the master branch. Now, the groups do not disappear when the window popup is closed.
> 
> **Exception: WexinAuthenticationHandler**
> 
> The exception is probably thrown because the redirect URL is not passed in the AuthenticationProperties. I made some modifications in the master branch to pass this information. Can you try again?
> 
> **Sms is still displayed under enroll credentials**
> 
> The algorithm used to check if the user has the claim was not correct and has been fixed in the master branch.
> 
> **When Credential is Updated, Add a Link to Redirect to the Previous Page**
> 
> The returnUrl was not passed in the HTTP request. This issue has been fixed in the master branch.
> 
> **Ignore unhandled exception**
> 
> have added logic in the Startup.cs to ignore the Developer Exception Middleware when the development mode is set to false. When an exception is thrown, you will be redirected to the /Error page.
> 
> **Email validation**
> 
> I have added email validation logic in the backend.
> 
> **Keep 2 fields (SMS & Email)**
> 
> The UI (SMS & email) has been updated to keep only two fields.
> 
> **Webauthn problem**
> 
> It is now possible to update the webauthn credential on the Identity Server website. The remove feature is also fixed.

Thanks for your hard work, I have tested it again, and the following problems still exist:
**API Resource**
When I don't tick the resource I want in the "Available resources" list and instead click the "Assign" button, the contents of the "Available resources" list will disappear.
**Email validation**
Are you sure you changed the logic? I tested the same thing as before. The verification should be determined after clicking the "Send confirmation code", if there is the same, stop sending the verification code and prompt that the same email already exists, instead of clicking the registration (or modify) prompt. SMS should be the same, judged after clicking "Send confirmation code".
**Webauthn problem**
Unfortunately, the problem still exists. When I add webauthn to the user on page 5001 and repeat the operation to add another one, two webauthn will be displayed below the credentials of the account, and only one can be deleted, while the other cannot be deleted all the time. Moreover, I find that webauthn also has a "Reset" button. When you click on it, there is a blank page, which is also shown at the end of the video, video:
[video.zip](https://github.com/simpleidserver/SimpleIdServer/files/14595855/video.zip)

**Comment by qq1176914912** [comment]
**Forgot password**
1、The Forgot Password feature also lacks a return button after sending and reconnecting.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/01dee38d-e190-46d7-baf8-4cfa9383f651)
2、At present, the password is retrieved through the mailbox, does he support other ways? How do I change the support? If not, there must be an email in the registration process, otherwise the password cannot be retrieved, is that the understanding?

**Comment by qq1176914912** [comment]
**ACR**
1、Every page in ACR will have a "Remember my login" when you click on it and what does that do? Is it the same as "Remember me" on the login page?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/0ad20471-e4ed-46a7-9afe-1ba36c090834)
2、SMS ACR when you do not enter the phone number directly click the two buttons in the page, no error message
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/ff72496c-26b7-40b3-9bb9-ea650afdee37)

**Comment by qq1176914912** [comment]
**Validity time of the verification code**
Where is the validity time of the verification code set? Using the console example, isn't the validity time of the verification code set here?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/61dc0bf1-1ce2-43b6-ab34-f33f8856b227)
If so, why am I using console in acr to send the CAPTCHA or display it for 30 seconds?
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/c033e295-ebf8-475a-9f89-cace1da41f0a)

**Comment by qq1176914912** [comment]
**TRANSLATORS**
Where is the sentence that disconnects the home page? I tried to translate it but I couldn't find it
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/d1e1cca1-58ff-4c28-b7b0-f418a920d43f)

**Comment by qq1176914912** [comment]
**Add Identity Provider**
1、When adding a third-party login, in the "Details" step, you can click Next even if the data is not empty:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/948df4e3-90ef-40d8-8d99-75d6995f4de9)/
2、In the "Details" step, fill in only one Name, after the successful addition, the list is blank:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f64994e3-e09e-4f9c-8900-575caca99bcd)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/3df085df-a5ec-4e48-8988-5490fe8aabee)
3、There was no nonnull judgment in the third "Properties" section, and I could add success even if my appid and appsecret were empty.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/674ba50f-a356-40a1-8dbe-6c5ec4127687)

**Comment by qq1176914912** [comment]
**Certificate Authorities**
The number of days filled with a negative number can also be successfully generated.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/1687917c-0d5d-4b83-a4a1-2e7f9cb8ac0b)

**Comment by qq1176914912** [comment]
**The popup error persists**
In the pop-up window of "Generate new key" on the client, as long as there is an error, even if the pop-up window is closed, the error still exists.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/a9464e16-ad85-41ee-926a-0a62e7f85ba5)
**Add user**
When you click "Add user" to add an existing user, there is no prompt.
**Remove realm**
At present, there are only adding realms, but not removing realms

**Comment by qq1176914912** [comment]
**Login method**
At present, the default login method of your system is to use the password. If I want to use the mailbox, webauthn, SMS login, where should I configure? How do you do that?

**Comment by qq1176914912** [comment]
**DistributedCacheConfiguration**
The previous implementation of sqlite, regarding the cache configuration of sqlite is written in the code:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/7bb7d09f-4b78-411c-a024-726a6d3b679b)
I found that the "conf.ConnectionString" in it can get the connection address, so I tried to change it, not to write it in the code, but to write it in the appsetting, as shown below:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/c4a4289f-13d3-4c35-b825-3412f9a428d5)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/e25b339c-aa4d-4cb3-9a40-aecde3ffc2f3)
But I found that if I did this, when I visited the 5002 address, the 5001 would get an error，But accessing the 5001 address does not present this problem.:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f4d2982c-7d56-4eb2-a19d-7798ebcf15b2)
In this way, it only changes the connection address to appsetting. Why does this problem occur? Is there a logic problem here?

**Comment by simpleidserver** [comment]
**API Resource**

The problem has been resolved in the master branch.

**Check Email**

The logic has been updated. Before sending the confirmation code, we now check if the user already exists.

**WebAuthn**

I removed the reset button from the UI. The WebAuthn credential is now added only once.

**Forgot Password**

We made some changes to display the back button in the UI and also on the confirmation screen. The reset password link is now sent only via email. To enroll the email, you can create a manual identity provisioning workflow consisting of two steps: password and email.

**Remember My Login**

I made some changes to display the "Remember Me" option only in the first authentication window.

**Validity of the Verification Code**

Indeed, the validity of the verification code is specified by the TOTP step field. The console authentication method is used only for development purposes.

**Translation**

This message originates from the Blazor framework.

**Add Identity Provider**

The name, display name, app ID, and app secret are now required parameters.

**API Resource**

The audience is now a required property.

**Certificate Authorities**

We are now checking if the number of days is greater than 1, and the previously generated certificate is no longer displayed.

**Popup Error Persistence**

This issue has been resolved.

**Remove Realm**

It is not a bug but a new feature. I have created ticket #716 to support it.

**Login Method**

The default login method can be specified in the DefaultAcrValue property. For example:

```
services.AddSIDIdentityServer(callback: cb =>
{
    cb.DefaultAcrValue = "pwd-email";
    if (!string.IsNullOrWhiteSpace(identityServerConfiguration.SessionCookieNamePrefix)) 
        cb.SessionCookieName = identityServerConfiguration.SessionCookieNamePrefix;
    cb.Authority = identityServerConfiguration.Authority;
}, cookie: c =>
{
    if(!string.IsNullOrWhiteSpace(identityServerConfiguration.AuthCookieNamePrefix)) 
        c.Cookie.Name = identityServerConfiguration.AuthCookieNamePrefix;
}, dataProtectionBuilderCallback: ConfigureDataProtection)
```

**Registration Workflow**

The demo link has been fixed and now redirects to the correct realm.

**Distributed Cache Configuration**

There was a small issue in the Startup.cs class where the distributed cache was using the wrong connection string. This issue has also been resolved in the master branch.

**Comment by qq1176914912** [comment]
**External identity providers**
Hello.
I am currently using the "POSTGRE" database, and when I delete all the contents of the "External identity providers" list in "Authentications" :
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f1e4402a-7837-4c76-afa6-eeaf2b26a707)
Then I restarted Project 5001, and I found that the project would try to insert data into the library again, resulting in an error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/2d6c6101-9656-441e-9628-0cbae1b8d067)
I also tested SQLITE, and he will do the same.

**Comment by qq1176914912** [comment]
Do you remember changing DateTime.UtcNow to DateTime.Now? When I was using postgresql, I found that when I performed "Add Certificate Authority", I would get an error, which said that postgresql only supports utc time. So I am "SimpleIdServer. IdServer/Api/CertificateAuthorities CertificateAuthoritiesController. Cs" has carried on the following changes:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/47414184-4dbd-492d-b4dc-c1715f4caadd)
Will this affect other database types?

**Comment by simpleidserver** [comment]
**Exception**

The exception has been resolved in the master branch. When the identity server is restarted, the authentication scheme providers are properly restored.

**Datetime**
As I explained in our previous conversation, DateTime.UtcNow should not be altered to DateTime.Now. 
Therefore, the backend code must remain unchanged. I have already implemented modifications in the administration website to convert all UTC datetimes to local datetimes: https://github.com/simpleidserver/SimpleIdServer/commit/046661330b95228182cde46e3e6a6a68deb93d37

**Comment by qq1176914912** [comment]
> **Exception**
> 
> The exception has been resolved in the master branch. When the identity server is restarted, the authentication scheme providers are properly restored.
> 
> **Datetime** As I explained in our previous conversation, DateTime.UtcNow should not be altered to DateTime.Now. Therefore, the backend code must remain unchanged. I have already implemented modifications in the administration website to convert all UTC datetimes to local datetimes: [0466613](https://github.com/simpleidserver/SimpleIdServer/commit/046661330b95228182cde46e3e6a6a68deb93d37)

**Datetime**
Yes, the previous modification was to display the local time on the 5002 address, which was not found when I used SQLITE before, but I found the problem when I used the POSTGRE database, when I tried to add a "Certificate Authority", there was a problem in 5001 when I clicked the save button:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/fe77269b-3853-4c56-836e-6bd0c3b19856)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/935cb134-ec76-4291-8a4c-4c3670b74358)
So I just changed the "CertificateAuthoritiesController" in the "Add" method.

**Comment by qq1176914912** [comment]
> > **Exception**
> > The exception has been resolved in the master branch. When the identity server is restarted, the authentication scheme providers are properly restored.
> > **Datetime** As I explained in our previous conversation, DateTime.UtcNow should not be altered to DateTime.Now. Therefore, the backend code must remain unchanged. I have already implemented modifications in the administration website to convert all UTC datetimes to local datetimes: [0466613](https://github.com/simpleidserver/SimpleIdServer/commit/046661330b95228182cde46e3e6a6a68deb93d37)
> 
> **Exception** I noticed your change, and when I cleared it, it will re-join the default login method. One problem is that users don't want "External identity providers" and just want the default account and password to log in, which is currently not possible. This is just my personal opinion, do you think it is necessary?
> 
> **Datetime** Yes, the previous modification was to display the local time on the 5002 address, which was not found when I used SQLITE before, but I found the problem when I used the POSTGRE database, when I tried to add a "Certificate Authority", there was a problem in 5001 when I clicked the save button: ![image](https://private-user-images.githubusercontent.com/79817742/314866319-fe77269b-3853-4c56-836e-6bd0c3b19856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODQ3OTcsIm5iZiI6MTcxMDk4NDQ5NywicGF0aCI6Ii83OTgxNzc0Mi8zMTQ4NjYzMTktZmU3NzI2OWItMzg1My00YzU2LTgzNmUtNmJkMGMzYjE5ODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAxMjgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNDJjZDMyNGJmMTBmMTEzYzBmMDc0YzgwZmE1YzM5Y2E0N2Y3NGQ5ZmJmMmRiYWFiMzJmN2QxY2EzYjkxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gFia1DqPhCxCao4K8c1tqO7fjxG77efYJ5My8UJ2aEI) ![image](https://private-user-images.githubusercontent.com/79817742/314857838-935cb134-ec76-4291-8a4c-4c3670b74358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODQ3OTcsIm5iZiI6MTcxMDk4NDQ5NywicGF0aCI6Ii83OTgxNzc0Mi8zMTQ4NTc4MzgtOTM1Y2IxMzQtZWM3Ni00MjkxLThhNGMtNGMzNjcwYjc0MzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAxMjgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzAwNWRlYmQ2Yjg2MGY3Yjk2M2Q3N2E0OTRlMjNmMzZiM2U5OWNlZGY1NzM4ZGVkMWIwMmQwNTk2MTAxMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LCU31UnAKpCkmcfCPzPlxPVeB_-Mbu7M7RHAIzt7Y9s) So I just changed the "CertificateAuthoritiesController" in the "Add" method.

**Exception**
I found that I could achieve the effect of not having "External identity providers" by creating a new "Realm" so that "External identity providers" would not appear on the login page.

**Comment by qq1176914912** [comment]
**Add user**
Hello.
When adding a user, if an existing user is added, there is no prompt or response after clicking the Add button
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/f5c952c5-0d6c-4915-8a31-4a48841bf9ab)

**Comment by qq1176914912** [comment]
**webauthn**
1、When I select "webauthn" in ACRS on page 5002:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/fcd69803-d461-463a-92ef-32c5e3c578a0)
Then enter an account that has not been bound to "webauthn" and click the "Authenticate" button to authenticate without any prompt
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/2dee36b4-d52a-4647-924a-428db13b4bbf)
5001 Error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/b8d1d133-4c83-4171-86a4-87ba5a9d6d2b)
I'm guessing it's because there's no way to check if an account is bound to "webauthn"?
2、When I pass the 5001 address, Enroll credentials for the account: After "webauthn", then go to "User details->Credentials" in 5002 to delete the newly added webauthn. When I refresh the page again after the deletion is complete, the deleted "webauthn" appears again.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/6675c7c7-d97d-4e6f-8750-eea7c0984676)

**Comment by qq1176914912** [comment]
**Validity of the Verification Code**
As you said, "the validity of the CAPTCHA is specified by the TOTP step field", when I set the TOTP step of the email to 300:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/db41eb23-8acb-4dc7-a0ec-611c36a4efec)
Then I click on email in 5002ACR:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/1eef28fa-e1c5-4734-9b38-452d21f6c946)
After sending the verification code, the valid time is still displayed as 30 seconds
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/4d39421c-5ad1-4019-8c15-2721cd927c35)

**Comment by simpleidserver** [comment]
**External Identity Providers Added**

If you prefer not to re-add the identity provider, you can modify the Program.cs file and comment out the `AddMissingAuthenticationSchemeProviders` procedure.

**PostgreSQL Problem**

The issue with the PostgreSQL database has been resolved in the master branch. Certificate datetimes are now converted to UTC in the UI.

**No Error in Add User Popup Window**

Error messages are now displayed in the UI popup window when an issue occurs.

**WebAuthn Credential Not Enrolled**

An error message is displayed when the user does not have a WebAuthn credential.

*TOTP Step**

I provided an incorrect explanation about the TOTP step. The fields OTP Algorithm, OTP Value, and TOTP Step, present in the authentication methods email, console, and mobile, are used to generate an OTP code, which will be sent with the reset password link.

**Cannot Remove WebAuthn**

This feature is functional on my local machine. I tested it with the latest version in the master branch with PostgreSQL.

**Comment by qq1176914912** [comment]
> **External Identity Providers Added**
> 
> If you prefer not to re-add the identity provider, you can modify the Program.cs file and comment out the `AddMissingAuthenticationSchemeProviders` procedure.
> 
> **PostgreSQL Problem**
> 
> The issue with the PostgreSQL database has been resolved in the master branch. Certificate datetimes are now converted to UTC in the UI.
> 
> **No Error in Add User Popup Window**
> 
> Error messages are now displayed in the UI popup window when an issue occurs.
> 
> **WebAuthn Credential Not Enrolled**
> 
> An error message is displayed when the user does not have a WebAuthn credential.
> 
> **TOTP Step**
> 
> I provided an incorrect explanation about the TOTP step. The fields OTP Algorithm, OTP Value, and TOTP Step, present in the authentication methods email, console, and mobile, are used to generate an OTP code, which will be sent with the reset password link.
> 
> **Cannot Remove WebAuthn**
> 
> This feature is functional on my local machine. I tested it with the latest version in the master branch with PostgreSQL.

Hello, thank you for your reply.
**Cannot Remove WebAuthn**
I downloaded your latest project again and tried it again, but it still failed to delete, and the 5001 project showed a 404 error when deleting. Database type I use "INMEMORY" to avoid deletion failure caused by data, the process can view my recorded video:
[video.zip](https://github.com/simpleidserver/SimpleIdServer/files/14740000/video.zip)

**Comment by simpleidserver** [comment]
*Credential identifier*
Thanks to your video, I understand the problem. 
The credential identifier contains a separator '/', hence a 404 error is returned. 
I have updated the technical identifier of the credential, and this exception should not occur anymore.

*TOTP*
Indeed, the TOTP set in the 'Authentications' is only used to reset the validity time of the password link. 
Currently, it is not possible to update the user's TOTP step, which is displayed in the authentication method. By default, the value is set to 30.

**Comment by qq1176914912** [comment]
> _Credential identifier_ Thanks to your video, I understand the problem. The credential identifier contains a separator '/', hence a 404 error is returned. I have updated the technical identifier of the credential, and this exception should not occur anymore.
> 
> _TOTP_ Indeed, the TOTP set in the 'Authentications' is only used to reset the validity time of the password link. Currently, it is not possible to update the user's TOTP step, which is displayed in the authentication method. By default, the value is set to 30.

Thank you for your reply
